class RESPONSE():
    OK = 200
    CREATED = 201
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    FORBIDDEN = 403
    NOT_FOUND = 404
    CONFLICT = 409
    TOO_MANY_REQUESTS = 429
    INTERNAL_SERVER_ERROR = 500
    SERVICE_UNAVAILABLE = 503
    GATEWAY_TIMEOUT = 504

class ROLES():
    USER = 3939
    EDITOR = 5739
    ADMIN = 9139

class STATUS():
    ERROR = "error"
    SUCCESS = "success"


class TASK_STATUS():
    UNCOMPLETED = "UNCOMPLETED",
    PENDING = "PENDING",
    COMPLETED = "COMPLETED",
